<?php $this->css($this->assetModule('css/admin.css')); ?>
<div class="clearfix">
    <p>
        <a class="btn btn-primary" title="<?php _e('Add campaign'); ?>"
           href="<?php echo $this->url('', array('controller' => 'campaign', 'action' => 'update')); ?>"><i
                class="fa fa-folder-open"></i> <?php _e('Add campaign'); ?></a>
    </p>

    <h3><?php _e('List of campaigns'); ?></h3>
    <table class="table table-striped table-bordered table-condensed">
        <tr>
            <th><?php _e('ID'); ?></th>
            <th><?php _e('Title'); ?></th>
            <th><?php _e('Join'); ?></th>
            <th><?php _e('Type'); ?></th>
            <th><?php _e('Time'); ?></th>
            <th><?php _e('Action'); ?></th>
        </tr>
        <?php foreach ($list as $campaign) { ?>
            <?php
            if ($campaign['status'] == 1) {
                $labelIdClass = 'label-success';
            } elseif ($campaign['status'] == 2) {
                $labelIdClass = 'label-warning';
            } elseif ($campaign['status'] == 3) {
                $labelIdClass = 'label-warning';
            } elseif ($campaign['status'] == 4) {
                $labelIdClass = 'label-warning';
            } elseif ($campaign['status'] == 5) {
                $labelIdClass = 'label-danger';
            }
            ?>
            <tr<?php if ($campaign['isExpire']) { echo ' class="danger"'; } ?>>
                <td><span
                        class="label <?php echo $labelIdClass; ?>"><?php echo $this->escape($campaign['id']); ?></span>
                </td>
                <td><?php echo $this->escape($campaign['title']); ?></td>
                <td><?php echo $this->escape($campaign['join']); ?></td>
                <td><?php switch ($campaign['subscription_type']) {
                        case 'email':
                            _e('Email');
                            break;

                        case 'sms':
                            _e('Sms');
                            break;

                        case 'both':
                            _e('Both');
                            break;
                    } ?></td>
                <td><?php echo $this->escape($campaign['time']); ?></td>
                <td>
                    <a class="btn btn-primary btn-xs" title="<?php _e('Edit'); ?>"
                       href="<?php echo $this->url('', array('action' => 'update', 'id' => $campaign['id'])); ?>"><i
                            class="fa fa-edit"></i> <?php _e('Edit'); ?></a>
                </td>
            </tr>
        <?php } ?>
    </table>
</div>