<?php $this->css($this->assetModule('css/admin.css')); ?>
<div class="clearfix">
    <?php if (!empty($list)) { ?>
        <h3><?php _e('List of peoples'); ?></h3>
        <table class="table table-striped table-bordered table-condensed">
            <tr>
                <th><?php _e('ID'); ?></th>
                <th><?php _e('First name'); ?></th>
                <th><?php _e('Last name'); ?></th>
                <th><?php _e('Email'); ?></th>
                <th><?php _e('Mobile'); ?></th>
                <th><?php _e('Subscription date') ?></th>
                <th><?php _e('Is user?'); ?></th>
            </tr>
            <?php foreach ($list as $people) { ?>
                <?php
                if ($people['status'] == 1) {
                    $labelIdClass = 'label-success';
                } else {
                    $labelIdClass = 'label-danger';
                } 
                ?>
                <tr>
                    <td><span
                                class="label <?php echo $labelIdClass; ?>"><?php echo $this->escape($people['id']); ?></span>
                    </td>
                    <td><?php echo $this->escape(isset($people['user']['first_name']) ? $people['user']['first_name'] : $people['first_name']); ?></td>
                    <td><?php echo $this->escape(isset($people['user']['last_name']) ? $people['user']['last_name'] : $people['last_name']); ?></td>
                    <td><?php echo $this->escape(isset($people['user']['email']) ? $people['user']['email'] : $people['email']); ?></td>
                    <td><?php echo $this->escape(isset($people['user']['mobile']) ? $people['user']['mobile'] : $people['mobile']); ?></td>
                    <td><?php echo _date($people['time_join']) . ' ' . date('H:i', $people['time_join']) ?></td>
                    <td class="text-center"><?php if ($people['isUser'] && !empty($people['user']['name'])) { ?>
                            <!-- Button trigger modal -->
                            <button type="button" class="btn btn-link btn-sm" data-toggle="modal" data-target="#peopleUser<?php echo $this->escape($people['id']); ?>">
                                <?php echo $this->escape($people['user']['name']); ?>
                            </button>
                            <!-- Modal -->
                            <div class="modal fade" id="peopleUser<?php echo $this->escape($people['id']); ?>" tabindex="-1" role="dialog" aria-labelledby="peopleUserLabel<?php echo $this->escape($people['id']); ?>">
                                <div class="modal-dialog" role="document">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <button type="button" class="close" data-dismiss="modal" aria-label="<?php _e('Close'); ?>">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                            <h4 class="modal-title" id="peopleUserLabel<?php echo $this->escape($people['id']); ?>"><?php _e('User information'); ?></h4>
                                        </div>
                                        <div class="modal-body">
                                            <pre><?php print_r($people['user']); ?></pre>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        <?php } else {
                            _e('No');
                        } ?></td>
                </tr>
            <?php } ?>
        </table>
        <div class="paginator">
            <?php echo $this->paginationControl($paginator, 'Sliding', 'paginator.phtml'); ?>
        </div>
    <?php } else { ?>
        <div class="alert alert-danger" role="alert">
            <?php _e('No one still join to subscription list'); ?>
        </div>
    <?php } ?>
</div>