<?php $this->css($this->assetModule('css/admin.css')); ?>
<div class="clearfix">
    <h3><?php _e('List of peoples'); ?></h3>
    <table class="table table-striped table-bordered table-condensed">
        <tr>
            <th><?php _e('ID'); ?></th>
            <th><?php _e('First name'); ?></th>
            <th><?php _e('Last name'); ?></th>
            <th><?php _e('Email'); ?></th>
            <th><?php _e('Mobile'); ?></th>
        </tr>
        <?php foreach ($list as $people) { ?>
            <?php
            if ($people['status'] == 1) {
                $labelIdClass = 'label-success';
            } elseif ($people['status'] == 2) {
                $labelIdClass = 'label-warning';
            } elseif ($people['status'] == 3) {
                $labelIdClass = 'label-warning';
            } elseif ($people['status'] == 4) {
                $labelIdClass = 'label-warning';
            } elseif ($people['status'] == 5) {
                $labelIdClass = 'label-danger';
            }
            ?>
            <tr>
                <td><span
                        class="label <?php echo $labelIdClass; ?>"><?php echo $this->escape($people['id']); ?></span>
                </td>
                <td><?php echo $this->escape($people['first_name']); ?></td>
                <td><?php echo $this->escape($people['last_name']); ?></td>
                <td><?php echo $this->escape($people['email']); ?></td>
                <td><?php echo $this->escape($people['mobile']); ?></td>
            </tr>
        <?php } ?>
    </table>
</div>