<?php $this->css($this->assetModule('css/front.css')); ?>
<div class="clearfix">
    <?php if (!empty($campaign['largeUrl'])) { ?>
        <div class="campaign-width-description">
            <h1 class="p-name" itemprop="name"><?php echo $this->escape($campaign['title']); ?></h1>
        </div>
        <div class="campaign-width-image">
            <img class="img-responsive" itemprop="image" src="<?php echo $campaign['largeUrl']; ?>"
                 alt="<?php echo $this->escape($campaign['title']); ?>">
        </div>
    <?php } else { ?>
        <div class="page-header">
            <h1 class="p-name" itemprop="name"><?php echo $this->escape($campaign['title']); ?></h1>
        </div>
    <?php } ?>
    <?php if (!empty($campaign['text_subscription'])) { ?>
        <div class="clearfix">
            <?php echo $campaign['text_subscription']; ?>
        </div>
    <?php } ?>
    <div class="clearfix">
        <div class="col-md-8 col-md-offset-2 col-xs-12 col-sm-12">
            <table class="table table-striped table-bordered table-condensed">
                <tr>
                    <td><?php _e('First name'); ?></td>
                    <td><?php echo $this->escape($people['first_name']); ?></td>
                </tr>
                <tr>
                    <td><?php _e('Last name'); ?></td>
                    <td><?php echo $this->escape($people['last_name']); ?></td>
                </tr>
                <tr>
                    <td><?php _e('Email'); ?></td>
                    <td><?php echo $this->escape($people['email']); ?></td>
                </tr>
                <tr>
                    <td><?php _e('Mobile'); ?></td>
                    <td><?php echo $this->escape($people['mobile']); ?></td>
                </tr>
            </table>
        </div>
    </div>
</div>